apiVersion: apps/v1
kind: Deployment
metadata:
  name: tools-lucasfaria-dev
spec:
  replicas: 1 # You can adjust the number of replicas based on your needs
  selector:
    matchLabels:
      app: tools-lucasfaria-dev
  template:
    metadata:
      labels:
        app: tools-lucasfaria-dev
    spec:
      containers:
        - name: tools-lucasfaria-dev
          image: tools-lucasfaria-dev:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
