version: '3.8'

services:
  api:
    image: lucasheriques/go-api:latest
    ports:
      - "4000:4000"
    platform: linux/amd64

  caddy:
    ports:
      - "80:80"
      - "443:443"
    platform: linux/amd64
