version: '3.8'

services:
  api:
    image: lucasheriques/go-api:latest
    container_name: api-container
    environment:
      - CGO_ENABLED=0
      - GOOS=linux
    restart: unless-stopped
    platform: linux/amd64

  caddy:
    image: caddy:latest
    container_name: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    platform: linux/amd64

volumes:
  caddy_data:
  caddy_config:
