services:
  api:
    image: lucasheriques/go-api:latest
    container_name: api-container
    environment:
      - CGO_ENABLED=0
      - GOOS=linux
    restart: unless-stopped
    platform: linux/amd64

volumes:
  caddy_data:
  caddy_config:
