services:
  api:
    image: lucasheriques/go-api:latest
    container_name: api-container
    ports:
      - "4000:4000"
    environment:
      - CGO_ENABLED=0
      - GOOS=linux
    restart: unless-stopped
    platform: linux/amd64
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:4000/v1/healthcheck || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  gotenberg:
    image: gotenberg/gotenberg:8
    ports:
      - "3000:3000"
